### ISSUE TITLE
iOS plugin fails to load

### ISSUE THREAD

**Issue by derekagraham78** [samwarnick/obsidian-simple-embeds#36] opened 2022-03-26 19:12 UTC
Updated then tried loading and it failed to load
Then tried to uninstall end reinstall same

**Comment by samwarnick** [comment] 2022-03-26 20:03
Thanks for reporting. This is a duplicate of #35 . Safari does not like one of the regular expressions I'm using. Should have a fix soon.

**Closed by samwarnick** 2022-03-26 20:03 UTC
